# Site settings
title: Bhavana
email: lasanghacr@yahoo.com
description: Su retiro personal...
baseurl: "" # the subpath of your site, e.g. /blog/
destination: ../appV2/www #out
url: "http://lasangha.org" # the base hostname & protocol for your site
include: [audio, img, js, css]
# Build settings
markdown: kramdown
